### PR TITLE
Add gtkosx_integration

### PR DESCRIPTION
**Pull request by drselump14**
- Add support to enable dock & OSX window manager integration

Related issue: #38

### CODE REVIEW

**Comment by zegervdv** [comment]
Can you add the HEAD version for girara as well?

**Comment by drselump14** [comment]
@zegervdv done! Thanks for the advice

**Comment by drselump14** [comment]
@zegervdv Any idea how to fix the CI?

**Comment by zegervdv** [comment]
Don't worry about it. I haven't had the time to make it work. 

Thanks for your contribution!

**Pull request merged**
